name: Update submodules

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Sync and update submodules
        run: |
          git submodule sync --recursive
          git submodule update --init --recursive
          git submodule update --remote --recursive

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: ".gitmodules _layouts _pages/Exercises assets code"
          commit_message: "Update submodules from parent"
